# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161222_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='owner_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='votes_lb',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='votes_ub',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userquestion',
            name='user_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
